name: Login to Majsoul

on:
  schedule:
    - cron: '5 23 * * *'  # 20:05 UTC time (5:05 a.m. Korean time)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute main.py
      run: python main.py
      env:
        UID: ${{ secrets.UID }}
        TOKEN: ${{ secrets.TOKEN }}
